name: whiteboard_sdk_flutter
description: A Flutter plugin that support Agora Interactive Whiteboard on Android and iOS.
version: 0.5.4
homepage: https://github.com/netless-io/Whiteboard-Flutter
repository: https://github.com/netless-io/Whiteboard-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.4.4+3
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4

flutter:
  assets:
    - assets/whiteboardBridge/